### ISSUE TITLE
setFeatureState with pmtiles 

### ISSUE THREAD

**Issue by marcosci** [am2222/mapbox-pmtiles#18]
Hey Majid!

Me again. Do you have any idea how to use `mapbox.setFeatureState`  with pmtiles?
I am trying to create a hover effect for polygons and I get the following error:

> Error: The sourceLayer parameter must be provided for vector source types.

Cheers
Marco

**Comment by marcosci** [comment]
Ah, I figured out the source of this. Somehow `generateId` or `promoteId` have no effect on pmtiles sources. Is that something that can be fixed?

**Comment by am2222** [comment]
Hi @marcosci let me debug it a bit! I suspect it should be related to the promoteId declaration
