### ISSUE TITLE
TypeError: i.destroy is not a function

### ISSUE THREAD

**Issue by marcosci** [am2222/mapbox-pmtiles#32]
Hey Majid!

Me again :) I hope you don't mind, but I am using your library now to display the content of an S3 storage dynamically.

If a user switches the datasource in a dropdown, I change the URL for the pmtiles source. To do that, I have to remove the layer and source, as with any other dataset in mapbox. However, if I do that with mapbox-pmtiles, I get the following error:
 
<img width="341" alt="image" src="https://github.com/user-attachments/assets/fe849ad1-628d-4daa-a3db-1337dc5411c0">

My logic is actually quite simple (I removed all the parts that are specific to the UI):

```
	$: if (...) {
		map.removeLayer('fill_pmtiles');
		map.removeSource('pmTileSourceName');
	} else if (...) {
		mapbox.Style.setSourceType(mapboxPmTiles.SOURCE_TYPE, mapboxPmTiles.PmTilesSource);
		
		map.addSource('pmTileSourceName', {
			type: mapboxPmTiles.PmTilesSource.SOURCE_TYPE,
			url: PMTILES_URL,
			minzoom: header.minZoom,
			maxzoom: header.maxZoom,
			bounds: bounds
		});

		map.addLayer({
			id: 'fill_pmtiles',
			source: 'pmTileSourceName',
			'source-layer': pmtile_selected.replace(/\./, '').replace('.pmtiles', ''),
			type: 'fill',
			paint: {
				'fill-color': '#0080ff', // blue color fill
				'fill-opacity': 0.5
			}
		});

	}
```

Is this somehow related to mapbox-pmtiles? Maybe the setsourcetype or so?
I use this pattern quite often and never had any issues before.

Sorry if this should not affect your library :)

Cheers
Marco

**Comment by am2222** [comment]
Hi @marcosci!

Thanks for the message! So I did a little checking and it appears it fails in the tile object.


If we look at the abstract layer we see this

https://github.com/mapbox/mapbox-gl-js/blob/main/src%2Fsource%2Fcustom_source.ts#L347

It seems they are trying to destroy the tile object! Can you debug your code and check if it fails in this step, please?

If you can update the sample code you created a while ago I can also debug it and find a solution fo it!

Thank you!

**Comment by marcosci** [comment]
Yeah, this is where it throws the error in the end:

<img width="277" alt="image" src="https://github.com/user-attachments/assets/f98fb346-de40-44db-95fe-4709211199a3">

... which matches your findings.

I can try to replicate this, do you know a list of 2, 3 open pmtiles files?

**Comment by am2222** [comment]
Hi @marcosci so I just pushed a quick fix for it! can you please check if it solves the issue?
